import React, { useEffect, useState } from 'react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { PlaySquare, FileText, Settings, CheckCircle, AlertTriangle } from 'lucide-react';
import { useAppContext } from '../context/AppContext';

interface Suite {
  id: string;
  name: string;
  type: string;
  mode: string;
  endpoints: number;
  cases: {
    total: number;
    passed: number;
    failed: number;
    skipped: number;
    pass_rate?: number;
  };
  has_results: boolean;
}

export function TestSuites() {
  const { projectName, token } = useAppContext();
  const [suites, setSuites] = useState<Suite[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!projectName) return;
    fetch(`/api/execution/suites?project_name=${projectName}`, {
      headers: { 'Authorization': `Bearer ${token}` }
    })
      .then(res => {
        if (!res.ok) throw new Error('Failed');
        return res.json();
      })
      .then(data => setSuites(data))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [projectName]);

  const executeSuite = async (suiteId: string, mode: string) => {
    try {
      const res = await fetch('/api/execution/run', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}` 
        },
        body: JSON.stringify({
          project_name: projectName,
          suite_id: suiteId,
          mode: mode,
          tests_path: 'tests/'
        })
      });
      if (res.ok) {
        alert("Execution started!");
      } else {
        alert("Failed to start execution.");
      }
    } catch (e) {
      alert("Error starting execution.");
    }
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto pb-12">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            <FileText className="h-6 w-6 text-primary" />
            Test Suites
          </h1>
          <p className="text-secondary mt-1 text-sm">
            View and manage test cases generated by the API and UI Agents.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4">
        {loading && (
          <Card className="p-8 bg-card text-center text-secondary">Loading test suites...</Card>
        )}
        {!loading && suites.length === 0 && (
          <Card className="p-8 bg-card text-center text-secondary">No test suites found. Use the Agent Chat to generate test cases.</Card>
        )}
        {suites.map((suite) => (
          <Card key={suite.id} className="p-4 flex justify-between items-center bg-card hover:bg-elevated transition-colors border border-border">
            <div className="flex gap-4 items-start">
              <div className="mt-1">
                {suite.has_results ? (
                  suite.cases.failed === 0 ? <CheckCircle className="text-green-400 h-5 w-5" /> : <AlertTriangle className="text-yellow-400 h-5 w-5" />
                ) : (
                  suite.type === 'API' ? <Settings className="text-secondary h-5 w-5"/> : <FileText className="text-secondary h-5 w-5"/>
                )}
              </div>
              <div>
                <h3 className="font-semibold text-primary">{suite.name}</h3>
                <div className="flex gap-3 text-xs text-secondary mt-2 flex-wrap">
                  <span className="bg-elevated px-2 py-0.5 rounded border border-border">
                    {suite.type}
                  </span>
                  {suite.has_results && (
                    <>
                      <span className="text-green-400">{suite.cases.passed} Passed</span>
                      <span className="text-red-400">{suite.cases.failed} Failed</span>
                      <span className="text-yellow-400">{suite.cases.skipped} Skipped</span>
                      {suite.cases.pass_rate != null && (
                        <span className="font-bold text-primary">{suite.cases.pass_rate}% Pass Rate</span>
                      )}
                    </>
                  )}
                  {!suite.has_results && (
                    <span>{suite.cases.total} Test Files</span>
                  )}
                  <span>Mode: {suite.mode}</span>
                </div>
              </div>
            </div>
            
            <div className="flex gap-2">
              <Button variant="secondary" size="sm">View Code</Button>
              <Button 
                size="sm" 
                className="flex items-center gap-1"
                onClick={() => executeSuite(suite.id, suite.mode)}
              >
                <PlaySquare className="h-4 w-4" />
                Run
              </Button>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}
