import jwt
from typing import Optional, List
from fastapi import Depends, HTTPException, status, Request
from fastapi.security import OAuth2PasswordBearer
from pydantic import BaseModel
from datetime import datetime, timezone

from backend.core.config import settings, get_fernet
from backend.core.auth.base import UserIdentity
from backend.core.auth.local import LocalPasswordAuthBackend

# Ensure the secret key file is generated by calling get_fernet once
get_fernet()

with open(settings.SECRET_KEY_PATH, "rb") as f:
    SECRET_KEY = f.read().decode("utf-8")
ALGORITHM = "HS256"

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/auth/login")
auth_backend = LocalPasswordAuthBackend()

class CurrentUser(UserIdentity):
    projects: List[str]

def get_current_user(request: Request, token: str = Depends(oauth2_scheme)) -> CurrentUser:
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username: str = payload.get("sub")
        role_name: str = payload.get("role")
        must_reset: bool = payload.get("must_reset_password")
        if username is None or role_name is None:
            raise credentials_exception
    except jwt.PyJWTError:
        raise credentials_exception
        
    projects = auth_backend.get_user_projects(username)
    
    # Store in request state for AuditLogMiddleware
    request.state.username = username
    
    return CurrentUser(
        username=username,
        role_name=role_name,
        must_reset_password=must_reset,
        projects=projects
    )

def require_project(project_name: str):
    """
    Dependency generator to enforce that the current user has access to the specified project.
    """
    def project_checker(request: Request, user: CurrentUser = Depends(get_current_user)):
        if user.role_name != "Admin" and project_name not in user.projects:
            raise HTTPException(status_code=403, detail="Forbidden: You do not have access to this project.")
        
        request.state.project_name = project_name
        return user
    return project_checker

def require_role(allowed_roles: List[str]):
    """
    Dependency generator to enforce that the current user has one of the specified roles.
    """
    def role_checker(user: CurrentUser = Depends(get_current_user)):
        if user.role_name not in allowed_roles:
            raise HTTPException(status_code=403, detail=f"Forbidden: Requires one of roles {allowed_roles}")
        return user
    return role_checker
