apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    app: qa-rag-qdrant
spec:
  serviceName: {{ .Release.Name }}-qdrant
  replicas: 1
  selector:
    matchLabels:
      app: qa-rag-qdrant
  template:
    metadata:
      labels:
        app: qa-rag-qdrant
    spec:
      containers:
        - name: qdrant
          image: {{ .Values.images.qdrant }}
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: qdrant-data
              mountPath: /qdrant/storage
  volumeClaimTemplates:
    - metadata:
        name: qdrant-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.qdrantSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    app: qa-rag-qdrant
spec:
  type: ClusterIP
  ports:
    - port: 6333
      targetPort: 6333
  selector:
    app: qa-rag-qdrant
