apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: qa-rag-pipeline
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  LLM_PROVIDER: {{ .Values.secrets.llmProvider | b64enc | quote }}
  LLM_MODEL_NAME: {{ .Values.secrets.llmModelName | b64enc | quote }}
  LLM_API_KEY: {{ .Values.secrets.llmApiKey | b64enc | quote }}
  EMBEDDING_PROVIDER: {{ .Values.secrets.llmProvider | b64enc | quote }}
  EMBEDDING_MODEL_NAME: {{ .Values.secrets.llmModelName | b64enc | quote }}
  EMBEDDING_API_KEY: {{ .Values.secrets.llmApiKey | b64enc | quote }}
  {{- if .Values.secrets.masterKey }}
  MASTER_KEY: {{ .Values.secrets.masterKey | b64enc | quote }}
  {{- end }}
