apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app: qa-rag-prometheus
spec:
  serviceName: {{ .Release.Name }}-prometheus
  replicas: 1
  selector:
    matchLabels:
      app: qa-rag-prometheus
  template:
    metadata:
      labels:
        app: qa-rag-prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.images.prometheus }}
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ .Release.Name }}-prometheus-config
  volumeClaimTemplates:
    - metadata:
        name: prometheus-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.prometheusSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app: qa-rag-prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: qa-rag-prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app: qa-rag-grafana
spec:
  serviceName: {{ .Release.Name }}-grafana
  replicas: 1
  selector:
    matchLabels:
      app: qa-rag-grafana
  template:
    metadata:
      labels:
        app: qa-rag-grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.images.grafana }}
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
  volumeClaimTemplates:
    - metadata:
        name: grafana-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.grafanaSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app: qa-rag-grafana
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: qa-rag-grafana
